[package]
name = "libfloresta-workshop"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.5"
rustreexo = "0.4.0"
futures = "0.3.30"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.95"
floresta = { git = "https://github.com/vinteumorg/floresta", version = "0.3.0" }
